[dev]
  publish = "_site"
  command = "npm run dev"
[build]
  command = "npm run build"
  functions = "netlify/functions/"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
[[redirects]]
  from = "/faqs"
  to = "/blog/faqs/"
  status = 301
[[redirects]]
  from = "/discord"
  to = "https://discord.gg/theclaw"
  status = 301
[[plugins]]
package = "netlify-plugin-inline-functions-env"
   [plugins.inputs]
    include = ["GOOGLE_PRIVATE_KEY"]
[[edge_functions]]
  function = "eleventy-edge"
  path = "/*"